name: instant_messaging_app
description: "ChatLink - Secure instant messaging app with QR code connectivity"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl_phone_field: ^3.1.0
  
  # Core dependencies
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # QR Code functionality
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.7

  # Authentication & Security
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # Real-time messaging
  socket_io_client: ^2.0.3
  web_socket_channel: ^2.4.0
  uuid: ^4.0.0

  # UI & Utils
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
